development:
  adapter: mysql
  host: localhost
  username: root 
  password:
  database: colcentric2
  
test: &TEST
  adapter: mysql
  host: localhost
  username: root 
  password:
  database: colcentric2_test

production:
  adapter: mysql
  host: localhost
  username: root 
  password:
  database: colcentric2_production

cucumber:
  <<: *TEST