# specify the 3-token values.
#USER: sdk-three_api1.sdk.com
#PWD: QFZCWN5HZM8VBG7Q
#SIGNATURE: A.d9eRKfd1yVkRrtmMfCFLTqa6M9AyodL0SJkhYztxUi8W9pCXF6.4NI
credentials: true
USER: isanch_1314690559_biz_api1.colcentric.com
PWD: 1314690595
SIGNATURE: AhPBcBlSFhK-w4LpQtUSbBMEHSB1An.iyXMZjlHG2yzsK.Aon.LL6DAO



# @@endpoints
#SERVER: api-3t.sandbox.paypal.com
#SERVER: api-3t.paypal.com
#SERVICE: /nvp/
# Proxy information of the client environment. @@proxy_info
USE_PROXY: false
proxy_address: nil
proxy_port: nil
proxy_user: nil
proxy_password: nil


# Information needed for tracking purposes. @@client_info
VERSION: 3.1.4
SOURCE: PayPalRubySDKV1.2.0


EC_URL: "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token="
DEV_CENTRAL_URL: "https://developer.paypal.com"
ENDPOINTS:
  :SERVER: "api-3t.sandbox.paypal.com"
  :SERVICE: "/nvp/"